### ISSUE TITLE
Images offset in drun mode

### ISSUE THREAD

**Issue by eoli3n** [petabyteboy/wofi-git-mirror#1]
When using ``-I``, i get on ico some ``x_offset`` on some desktop entries:

![2020-05-08T00:51:52,050916943+02:00](https://user-images.githubusercontent.com/14223657/81352151-1ea0cb00-90c6-11ea-89de-69aaf6443b0a.png)

Is that a bug ?

-----

Also, i want to resize images to fit the text size, what should i use inside ?
```
#img{
}
```

**Comment by petabyteboy** [comment]
Hi, first of all I want you to be aware that this is not the development repository of wofi. The wofi development takes place in the hg repository at https://hg.sr.ht/~scoopta/wofi. This git repository was created just for convenience of people who are familiar with git.
If you want to contact the wofi developers, please create an issue [here](https://todo.sr.ht/~scoopta/wofi) (as mentioned in the readme).

However I think I can answer your question, so it may not be necessary. Take a look at this screenshot of an unstyled wofi prompt:

![screenshot](https://user-images.githubusercontent.com/3250809/81357388-cc66a680-90d3-11ea-9096-702f38a9bd2d.png)

As you can see some desktop files define specific actions and those have a little arrow in their entry to indicate that the entry can be expanded to show more related actions. I would guess that you are not seeing the arrow for some reason, but it still takes up space.
If this answers your question, please close the issue, thanks!

**Comment by eoli3n** [comment]
Thanks for your answer.
It does explain, but doesn't solve :) Do you think there is a way to disable that feature ? Or to still it ? How to debug wofi elements ?

You didn't see my second question
> Also, i want to resize images to fit the text size, what should i use inside #IMG CSS ?

**Comment by petabyteboy** [comment]
Hi,

> It does explain, but doesn't solve :) Do you think there is a way to disable that feature ? Or to still it ? How to debug wofi elements ?

The structure of the wofi elements is described [here](https://www.mankier.com/7/wofi). Unfortunately here are severe limitations about what properties can be used with Gtk styling (https://developer.gnome.org/gtk3/stable/chap-css-overview.html). 
I used trial and error for debugging, and found this (rather hacky) solution:

```
expander .entry {
        margin-left: -15px;
}
```

> Also, i want to resize images to fit the text size, what should i use inside #IMG CSS ?

According to https://www.mankier.com/5/wofi, the image size can be set in the config file. The configuration setting is called `image_size`.

**Comment by eoli3n** [comment]
Nice ! Thanks a lot. Didn't see image_size in man, sorry for that.

A last thing, is there a way to get a dynamic height from line count ?

**Comment by petabyteboy** [comment]
Phew, no idea about the dynamic height. Wofi might need code changes to support that, not sure.
I just wanted to ask you about your theme, maybe you can add it to your dotfiles?

**Comment by eoli3n** [comment]
I already do : https://github.com/eoli3n/dotfiles/tree/wayland/roles/wofi
But i was meaning, a centralized place. Thanks for all your help
