### ISSUE TITLE
set wofi to 100% width size

### ISSUE THREAD

**Issue by eoli3n** [petabyteboy/wofi-git-mirror#2]
Is there a way to tell wofi to use 100% of the current display size ? as i did with rofi here
![rofi](https://raw.githubusercontent.com/eoli3n/dotfiles/master/screenshots/chrome-rofi.png)

**Comment by petabyteboy** [comment]
Hi, again the disclaimer I already gave for your first issue, but I think I can help here as well:

A quick search shows that this feature was implemented and if your version of wofi is recent enough, you should be able to do `--width "100%"`. Good luck!

https://todo.sr.ht/~scoopta/wofi/63
https://hg.sr.ht/~scoopta/wofi/rev/8389ef9fc5d41f2e788c8e564e59a2c9e28295b6

**Comment by eoli3n** [comment]
Moved to ``wofi-hg`` package on archlinux did the trick. Thanks !
